name: learn_chinese_sudongpo
description: 学中文·苏东坡 V0.8
publish_to: 'none'
version: 0.8.0+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - 55A50A20-27AF-491F-B737-712C4A461847.png
    - 9869CB58-6C3C-4D8F-8693-CB3BF04B0F62.png
    - 16F1DCC9-0A88-4597-ADC5-1B7B5EBE3A65.png
    - 72662586-3399-4E22-B9C3-75EE46301453.png
    - D5F5EAD4-74A3-44B1-B457-0ED596533F44.png
    - 7241CC18-F9EC-43BE-BB04-A29E72E37882.png
